[package]
name = "jclosure"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
j4rs = { workspace = true }
j4rs_derive = { workspace = true }
jbc_base = { path = "../jbc_base" }
jbc_derive = { path = "../jbc_derive" }