[package]
name = "jbc_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "*"
proc-macro2 = "*"
zdcz = { git = "https://github.com/worksoup/zdcz.git" }