[package]
name = "jbc_base"
version = "0.1.0"
edition = "2021"

[dependencies]
j4rs = { workspace = true }
j4rs_derive = { workspace = true }
jbc_derive = { path = "../jbc_derive" }
wnewtype = {git = "https://github.com/worksoup/wnewtype.git"}